### ISSUE TITLE
Doubt about inputs

### ISSUE THREAD

**Issue by EudaldJuvanteny** [jiangyuan2li/Deep-Spatio-Temporal#2]
Hello, we wanted to test your algorithm with our data. Is a windfarm in France.

We have some doubts:
1. Our wind speed historical data are not exactly in the same location as tubrines locations. But we can update de code in a way that for each turbine the algorithm take the closer wind speed locations?
2. Our wind speed historical data are in vector form (u,v). Should we do the module of the vector to get the same speed as your data, or maybe we could try te algorithm with our data directly, so for each location we have two values, the componente u and v.
Thanks for your attention.

Regards

**Comment by jiangyuan-li** [comment]
It sounds reasonable to use the closest location with wind speed records. However, it may introduce extra error depending on how close of the closest location (compared with other locations). 

I didn't see any drawback if you could use the vector form of wind speed. Especially if you also know the position of turbine blades, it could provide more information for power forecasting.

Your work sounds very exciting. Looking forward to reading it!
