### ISSUE TITLE
about mae and rmse

### ISSUE THREAD

**Issue by hasaki1999** [jiangyuan2li/Deep-Spatio-Temporal#4]
hello， I would like to ask that when calculating the rating indicators, y_ true and y_ preddid pred add 1 and divide by 2,thank you.

**Comment by jiangyuan-li** [comment]
The response is in the range [0,1]. It was recast into [-1,1] in preprocessing for computational purposes with other weighting ideas incorporated in training. When reporting the test error, we transform it back and report it in the original scale. The calculation you mentioned is just the reverse of preprocessing transformation.
