### ISSUE TITLE
Data about 100 wind turbines in Wyoming

### ISSUE THREAD

**Issue by 1229308805** [jiangyuan2li/Deep-Spatio-Temporal#5]
When run getNRELdata.py on my machine， it shows "ValueError: no endpoint set".  I think the URL:"/nrel/wtk/conus/wtk_conus_2012.h5" is not available right now. I want to know how can I get this dataset， thanks a lot！

**Comment by jiangyuan-li** [comment]
Please refer to https://github.com/NREL/hsds-examples about the access of NREL data.
