### ISSUE TITLE
Only get 99 wind turbines in Wyoming

### ISSUE THREAD

**Issue by Neo-101** [jiangyuan2li/Deep-Spatio-Temporal#6]
Thanks for the open-source code. After I ran the getNRELdata.py, the wind_speed.csv only contains 99 wind turbines, not 100. Could you tell me how to get data of 100 wind turbines, please?

**Comment by jiangyuan-li** [comment]
It is potentially caused by updates in the database. The code may be outdated. You could try different thresholds on longitudes and latitudes to select your interested regions. The region we pick exactly follows reference [20] (Zhu et al 2020) cited in our paper.
