### ISSUE TITLE
How can I see the results

### ISSUE THREAD

**Issue by Hao-Q-Q** [jiangyuan2li/Deep-Spatio-Temporal#7]
I have finished the train,run the train.py and getNRELdata.py,but nothng happens, I don't know how to see the results. Is this result  a model??  In a word,I don't  know what is the output .I have seen the article,but I can't understand.Because I am a new in this field and I can't find others help me.Thank you so much for your help

**Comment by Xingyyy01** [comment]
Did you notice the folder: outputs? When you finish running the code, several files will appear in this folder, which are the predicted errors and the parameters of the model.

**Comment by z2450590318** [comment]
用h5pyd模块获取数据集显示端点错误，如何解决？
